
# tap repositories and their packages

tap homebrew/core
brew aom
brew autoconf
brew bdw-gc
brew c-ares
brew cairo
brew carthage
brew ccat
brew cocoapods
brew dav1d
brew duti
brew ffmpeg
brew fish
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzy
brew gdbm
brew gettext
brew giflib
brew glib
brew gmp
brew gnutls
brew go
brew gobject-introspection
brew graphite2
brew guile
brew harfbuzz
brew highlight
brew icu4c
brew jemalloc
brew jid
brew jpeg
brew jq
brew lame
brew leptonica
brew libarchive
brew libass
brew libb2
brew libbluray
brew libev
brew libevent
brew libffi
brew libidn2
brew libogg
brew libpng
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libvidstab
brew libvorbis
brew libvpx
brew little-cms2
brew lua
brew lua@5.1
brew lz4
brew lzo
brew mas
brew mpv
brew mujs
brew ncurses
brew nettle
brew nghttp2
brew oniguruma
brew opencore-amr
brew openjpeg
brew openssl@1.1
brew opus
brew p11-kit
brew pcre
brew pcre2
brew pixman
brew pkg-config
brew pyenv
brew rav1e
brew rbenv
brew readline
brew rename
brew rtmpdump
brew rubberband
brew ruby-build
brew sdl2
brew snappy
brew speedtest-cli
brew speex
brew sphinx-doc
brew sqlite
brew srt
brew starship
brew swiftformat
brew tesseract
brew theora
brew tig
brew tree
brew uchardet
brew unbound
brew vapoursynth
brew w3m
brew webp
brew wget
brew x264
brew x265
brew xvid
brew xz
brew youtube-dl
brew zeromq
brew zimg
brew zsh
brew zsh-completions
brew zstd

tap homebrew/bundle

tap homebrew/cask-fonts
cask font-source-han-code-jp

tap homebrew/cask
cask adobe-acrobat-reader
cask alfred
cask appcleaner
cask atom
cask bathyscaphe
cask clipy
cask google-chrome
cask google-japanese-ime
cask hyperswitch
cask iina
cask insomnia
cask iterm2
cask karabiner-elements
cask keepingyouawake
cask keyboardcleantool
cask provisionql
cask qlimagesize
cask qlmarkdown
cask qlprettypatch
cask qlstephen
cask qlvideo
cask quicklook-csv
cask quicklook-json
cask quicklookase
cask slack
cask sourcetree
cask suspicious-package
cask table-tool
cask typora
cask visual-studio-code
cask vlc
cask webpquicklook

tap jhawthorn/fzy

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask betterzipql
cask p4merge

# App Store applications
appstore 1180531112 DeskApp for YouTube (1.3)
appstore 682658836 GarageBand (10.4.2)
appstore 668208984 GIPHY CAPTURE (4.1)
appstore 408981434 iMovie (10.2.1)
appstore 409183694 Keynote (10.3.8)
appstore 715768417 Microsoft Remote Desktop (8.0.30030)
appstore 1335612105 MKPlayer (1.4.2)
appstore 1218784832 NamingTranslator (1.0.1)
appstore 409203825 Numbers (10.3.5)
appstore 409201541 Pages (10.3.5)
appstore 1288063933 PasteTheType (1.1)
appstore 1007457278 Realm Browser (3.0.1)
appstore 1449412482 Reeder (4.2.8)
appstore 1477385213 Save to Pocket (1.1)
appstore 1114363220 TermHere (1.1)
appstore 425424353 The Unarchiver (4.2.4)
appstore 1480933944 Vimari (2.1.0)
appstore 1472432422 Wayback Machine (1.4)
appstore 497799835 Xcode (12.2)
