tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "jhawthorn/fzy"
brew "carthage"
brew "duti"
brew "fzy"
brew "git"
brew "jq"
brew "mas"
brew "rbenv"
brew "rename"
brew "swiftformat"
brew "tig"
cask "alfred"
cask "appcleaner"
cask "atom"
cask "bettertouchtool"
cask "clipy", args: { appdir: "/Applications" }
cask "google-chrome"
cask "google-japanese-ime"
cask "iina", args: { appdir: "/Applications" }
cask "iterm2"
cask "karabiner-elements"
cask "keepingyouawake", args: { appdir: "/Applications" }
cask "keyboardcleantool", args: { appdir: "/Applications" }
cask "p4v", args: { appdir: "/Applications" }
cask "slack", args: { appdir: "/Applications" }
cask "sourcetree"
mas "BetterSnapTool", id: 417375580
mas "Realm Browser", id: 1007457278
mas "TermHere", id: 1114363220
mas "The Unarchiver", id: 425424353
